// Generated by gencpp from file server/CurrentClients.msg
// DO NOT EDIT!


#ifndef SERVER_MESSAGE_CURRENTCLIENTS_H
#define SERVER_MESSAGE_CURRENTCLIENTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server
{
template <class ContainerAllocator>
struct CurrentClients_
{
  typedef CurrentClients_<ContainerAllocator> Type;

  CurrentClients_()
    : clientIds()  {
    }
  CurrentClients_(const ContainerAllocator& _alloc)
    : clientIds(_alloc)  {
    }



   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _clientIds_type;
  _clientIds_type clientIds;




  typedef boost::shared_ptr< ::server::CurrentClients_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server::CurrentClients_<ContainerAllocator> const> ConstPtr;

}; // struct CurrentClients_

typedef ::server::CurrentClients_<std::allocator<void> > CurrentClients;

typedef boost::shared_ptr< ::server::CurrentClients > CurrentClientsPtr;
typedef boost::shared_ptr< ::server::CurrentClients const> CurrentClientsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server::CurrentClients_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server::CurrentClients_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'server': ['/home/evan/Code/cloud-robotics/server/src/server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::server::CurrentClients_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server::CurrentClients_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server::CurrentClients_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server::CurrentClients_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server::CurrentClients_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server::CurrentClients_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server::CurrentClients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "321d5ee1fa12e83bad0a9350af092cea";
  }

  static const char* value(const ::server::CurrentClients_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x321d5ee1fa12e83bULL;
  static const uint64_t static_value2 = 0xad0a9350af092ceaULL;
};

template<class ContainerAllocator>
struct DataType< ::server::CurrentClients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server/CurrentClients";
  }

  static const char* value(const ::server::CurrentClients_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server::CurrentClients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[] clientIds\n\
";
  }

  static const char* value(const ::server::CurrentClients_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server::CurrentClients_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.clientIds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CurrentClients_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server::CurrentClients_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server::CurrentClients_<ContainerAllocator>& v)
  {
    s << indent << "clientIds[]" << std::endl;
    for (size_t i = 0; i < v.clientIds.size(); ++i)
    {
      s << indent << "  clientIds[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.clientIds[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_MESSAGE_CURRENTCLIENTS_H
